### ISSUE TITLE
Modal "darkroom" menu in Facebook closes after pic download

### ISSUE THREAD

**Issue by brunsworks** [TheRealMarnes/doubleclick-image-downloader#13]
Is there a way to work around Facebook's modal darkroom to keep it open after using Double-Click Image Downloader? It's only a minor thing, and is really not a bug, but a feature request, but GitHub doesn't seem to differentiate.

**Comment by TheRealMarnes** [comment]
I'm not familiar with facebook... Is it like some sort of screen overlay that closes when you click it? How does DID usage fit into that?

**Comment by brunsworks** [comment]
That's exactly how it behaves.

**Comment by TheRealMarnes** [comment]
Can you get me a screenshot? I dont know anything yet

**Comment by brunsworks** [comment]
It looks like this:


(The image is in somewhat poor taste, so I apologize if it’s considered NSFW, but those are flip-flops, I swear.)




Perry

**Comment by TheRealMarnes** [comment]
There's nothing in your post...

**Comment by brunsworks** [comment]
Ah. Sorry about that. The message from GitHub said I could reply by email, but didn't say it wouldn't put in attachments.

[https://app.box.com/s/7i4v4d0yfzxlk3cjkkl0u6wyz1741iu2](url)

**Comment by TheRealMarnes** [comment]
I know something I can try but I don't know if it can be fixed. The whole problem with this kind of thing is that my addon's button and the website can't be kept separated, so at times they'll interfere with each other...

**Comment by brunsworks** [comment]
I figured that it might be an unresolvable issue, but it never hurts to ask!

Even so, Double-Click Image Downloader is still a great extension! Thank you very much for writing it.

Perry

**Comment by TheRealMarnes** [comment]
I just realized I'm a dunce and there is a simple other thing I can try: my button can "swallow" your mouseclick so normally facebook won't even be able to tell you did it. I don't maintain the firefox variants anymore though.

**Comment by brunsworks** [comment]
Cool idea!

Thank you for continuing to look into the issue, even if Firefox is no
longer in the equation.

Perry

**Comment by TheRealMarnes** [comment]
Hopefully soon mozilla will finish chrome addon support and the firefox versions wont be needed anymore

**Comment by TheRealMarnes** [comment]
I published a new version to AMO with hopefully a fix for your problem... I hope it passes review, I can't really know if it even works cause I don't have firefox anymore. There's also still a chance websites will intercept the click event before I can stop it

**Comment by TheRealMarnes** [comment]
It's live now, could you update and test?

**Comment by brunsworks** [comment]
Wow! Will do!

**Comment by brunsworks** [comment]
It works seamlessly! Thank you so much for taking so much time and effort on this.

Perry

**Comment by TheRealMarnes** [comment]
Glad to help. It's actually a good thing for me too, especially because this was all an oversight in standard web design. Swallowing the mouse event that essentially only my code should care about since it's on my injected button is good practice, should've done that from the start. Thanks for bringing it up
