### ISSUE TITLE
Request for similar extension

### ISSUE THREAD

**Issue by Gitoffthelawn** [TheRealMarnes/doubleclick-image-downloader#7]
Would you consider writing a Firefox extension to do something similar for PDF files?: double-click on a link to a PDF file to save it to a user-specified folder.

**Comment by TheRealMarnes** [comment]
Sorry, but no. Ive stopped using firefox and wont make new addons for it/update the old ones anymore (except for minor stuff on the most popular ones). Ive ported everything to chrome instead.

The concept of your idea is also just too rare and case-specific imho.

Also, have you tried alt-clicking? :p

**Comment by Gitoffthelawn** [comment]
No problem.  Never hurts to ask! :-)

Once Firefox goes to Web Extensions, are you going to make all you goodies available on Firefox again?  I think the code is supposed to transfer between Chrome and Firefox easily.

Thanks for the idea of alt-clicking.  I gave it a try, and unfortunately it didn't do anything different.  It still shows the dialog box asking whether to open the file or save it.  I can tell it to always save the file, but then I have to remember to go into the Options and remove that setting each time.  Good idea, though.

**Comment by TheRealMarnes** [comment]
I think you might need to read this: https://support.mozilla.org/en-US/questions/929585
tl, dr: about:config browser.altClickSave=true

Always worked like a charm for me to insta-download any link I alt-clicked on.

As for your other question: when that stuff happens, that'll probably be the end of my addons. I've had it with mozilla and everything they do, and with how firefox has steadily been going down the drain. I have no interest in having to spend a lot of time and effort on a bunch of addons that I can't use and that are only for a browser I don't even want to use anymore.

If mozilla has any shred of intelligence left, they'll implement chrome's sdk as part of their big new move, allowing chrome addons to work almost seamlessly in firefox, negating the need for ports. Knowing mozilla, that's not what they'll do, and separate ports of addons will still need to be made.
